# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Partition of a graph given its centers
#' 
#' Greedy partition blah blah blah
#' @title Graph partition
#' @param neighbors A matrix defining a the links between the graph nodes.
#' @param centers The desired centers to start the algorithm
#' @return a vector indicating the cluster center for each graph node.
#' @author Marcelo Costa
RcppPartition <- function(neighbors, centers) {
    .Call('_gbdcd_RcppPartition', PACKAGE = 'gbdcd', neighbors, centers)
}

#' Generate frequency matrix
#' 
#' Frequency matrix
#' @title Frequency matrix generation
#' @param partitions A vector indicating the cluster center for each graph node.
#' @return a matrix.
#' @author Leandro Mineti
RcppFreqMatrix <- function(partitions) {
    .Call('_gbdcd_RcppFreqMatrix', PACKAGE = 'gbdcd', partitions)
}

